### PR TITLE
Add optional dependencies to `setup.py`

### PR DESCRIPTION
**Pull request by Crozzers**
Previously, if a user wanted to make sure optional features of markdown2 (such as code syntax highlighting) were enabled and working, they would have to know to install the optional dependencies (EG: Pygments) for these features to work.
This PR adds the `extras_require` key to `setup.py` to define these optional dependencies, enabling users to do:
```
pip install markdown2[code_syntax_highlighting]
```
To install markdown2 as well as Pygments>=2.7.3 (the earliest version I found that still passes all tests) for code highlighting.

I also added an "all" extra that automatically combines all the other extras to allow a short, convenient and easily memorable way to make sure all optional dependencies are installed.
```
pip install markdown2[all]
```

### CODE REVIEW

**Comment by nicholasserra** [comment]
Have the docs on this handy? I've seen it used but never implemented. LGTM though. Will prob do a release after this.

**Comment by Crozzers** [comment]
The [setuptools docs](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html?highlight=extras_require#optional-dependencies) explain how to define optional dependencies in a `pyproject.toml`/`setup.cfg`/`setup.py` file and I found [this stackoverflow answer](https://stackoverflow.com/a/13681679) on how the user might install them.

Unfortunately PIP doesn't provide a way to list the extras that a package provides but that's why I included the `all` extra and added it to the readme install instructions

**Comment by nicholasserra** [comment]
I pushed this up to test pypi and tested all the cases and appears to work correctly, thanks!

**Comment by nicholasserra** [comment]
Also cut a 2.4.5 release just for this.

**Pull request merged**
