### PR TITLE
Added Numbering

### PR DESCRIPTION
**Pull request by ewankirk**
Numbering is described in the docstring for the _do_numbering method.

A generic numbering capability which can be used for equations,
figures, tables etc.  Could also be used for footnotes if required.  Still in design mode so looking for comments.

### CODE REVIEW

**Comment by ewankirk** [comment]
Doh!  Left the debugging print statements in the file.  Apologies.

**Comment by nicholasserra** [comment]
This looks good to me. Should we pull out the lengthy docstring at this point? Assuming we want to add it to the wiki. A shorter version would be appropriate.

**Comment by ewankirk** [comment]
Ok, this has been done.  When this is live I'll add an extensive wiki entry.

I've run all the tests.  I'm getting failures on the pygments based tests which may be my customised version of pygments.  

What's the next stage?  I'm a little new to git (I use CVS mostly) so I'm not sure how this branch gets merged and released.

**Comment by nicholasserra** [comment]
Thank you. Tests look fine in CI, so you're probably seeing failures because of your customized pygments. Now that you mention it, we really need to add some unit tests to this. Check out some of the closed PRs to see examples of how others have added tests for new extras. 

After tests are added, i'll merge this into master. It will then go out with the next release :)

**Comment by ewankirk** [comment]
Cool.  I've written some tests.  Given the fairly simple syntax of the numbering system, there isn't much to test.  Once you're ready to release, I'll add the documentation on the Wiki,

**Comment by nicholasserra** [comment]
Looks like there's failures in CI in master. Once I patch that up we'll get this merged in.

**Comment by ewankirk** [comment]
I hope that's not my fault!  Let me know if there's anything I can do.

**Pull request merged**
