### PR TITLE
fixing  `cuddled-lists` with a single list item

### PR DESCRIPTION
**Pull request by hmagdy**
this hotfix is mainly the resolution of 
https://github.com/trentm/python-markdown2/issues/286

### CODE REVIEW

**Comment by nicholasserra** [comment]
Hello, thanks for the PR! 

In those test changes, was the addition of those tabs just to make the test pass with your changes? if it was a side effect of the patch and unrelated I wouldn't want to introduce a change like that.

Or is that rest change related to your fix?

**Comment by hmagdy** [comment]
@nicholasserra the test changes are required and make sense too, as you can see at any markdown editor, the below lines "old lines" (without tabs)
```
Here is an asterisk,
* What do you think
about it?

I suggest using version
1. Oops, now this line is treated
as a sub-list.
```
should be marked as bulleted and numeric list like:
-----
Here is an asterisk,
* What do you think
about it?

I suggest using version
1. Oops, now this line is treated
as a sub-list.
-----

So I think the correct test files are these new files (with tabs)

```
Here is an asterisk,
    * What do you think
about it?

I suggest using version
    8. Oops, now this line is treated
as a sub-list.
```

should be marked as none bulleted or numeric list like:
-----
Here is an asterisk,
    * What do you think
about it?

I suggest using version
    8. Oops, now this line is treated
as a sub-list.

-----

**Comment by hmagdy** [comment]
@nicholasserra  Added new test cases for the fix. which cover lists with single item.

**Comment by nicholasserra** [comment]
Awesome thank you!

**Pull request merged**
