### PR TITLE
Fix syntax warnings in test suite

### PR DESCRIPTION
**Pull request by Crozzers**
This PR fixes a number of syntax warnings being raised in the test suite regarding invalid escape sequences. I also modified the test runner to make these warnings much more visible in the future

### CODE REVIEW

**Comment by nicholasserra** [comment]
LGTM

**Comment by nicholasserra** [comment]
Needs a rebase or merge in

**Comment by Crozzers** [comment]
Rebased onto master

**Comment by nicholasserra** [comment]
Thanks!

**Pull request merged**
