### PR TITLE
Fix some pep8 format with flake8 and support new feature.

### PR DESCRIPTION
**Pull request by keysona**
Some block comments:
```
#---xx
```
to
```
# ---xx
```

And some errors：trailing semicolon in python statement.
Like this：
```
_bq_one_level_re_spoiler = re.compile('^[ \t]*>[ \t]*?![ \t]?', re.M);
```

**New feature**:
A link with "_blank" in target attribute.
For example : 
```
[Ref](http://www.example.com)
```
To
```
<p><a target="_blank" href="http://www.example.com">Ref</a></p>
```

extras option is "link-with-blank".

### CODE REVIEW

**Comment by keysona** [comment]
#213

**Comment by keysona** [comment]
#213

**Comment by nicholasserra** [comment]
Thanks! 

So the idea here is that when you turn on the `link-with-blank` extra, any links in markdown will have `target="_blank"`?

**Comment by keysona** [comment]
@nicholasserra 

Yes, like ```nofollow```.

Maybe this extras option name ```link-with-blank```  is too long?

I think it can be shortest,  maybe ```blank``` or ```_blank```?

**Comment by nicholasserra** [comment]
Gotcha, cool. I don't think it's too long, but I think it's hard to understand. How about `target-blank-links`?

**Comment by keysona** [comment]
@nicholasserra 
Good name!
I agree to use ```target-blank-links```, it really easy to understand!
Now I change the name:-).

**Comment by nicholasserra** [comment]
Thanks!

**Comment by keysona** [comment]
#213

**Pull request merged**
