### PR TITLE
fixed: incorrect parsing nested backtick block

### PR DESCRIPTION
**Pull request by skywind3000**
fix: https://github.com/trentm/python-markdown2/issues/327

### CODE REVIEW

**Comment by nicholasserra** [comment]
Looks like a bunch of tests failing. Also missing a test for this fix. Is there any way to accomplish this by fixing the original regex? Thanks!

**Comment by skywind3000** [comment]
I will try to correct the testing failure, and IMO it is impossible to fix issue #333, regex is stateless but counting the number of starting backticks and matching the same number of backticks at the end require a stateful parsing method.

Feel free to close this if you have better solution for the nested backtick blocks, before that I will continue trying this way.

**Comment by kylepolich** [comment]
Any movement on this?  We want to use `markdown2` but we are relying on it parsing markdown in a manner similar to other parsers.

**Comment by nicholasserra** [comment]
Looks like tests still failing on it. If you have another patch for this PRs are welcome. Thanks!

**Pull request closed without merging**
