### PR TITLE
Add tasklist extra

### PR DESCRIPTION
**Pull request by liguangsheng**
Add tasklist extra

See [Issue #216 ](https://github.com/trentm/python-markdown2/issues/216)

### CODE REVIEW

**Comment by nicholasserra** [comment]
Thanks for the PR :)

Looks like this is failing a bunch of tests. Run `make testone` on your machine to run the test suite. We also only accept patches with test coverage. Please reference other PRs to see an example of a test being added.

**Comment by nicholasserra** [comment]
Replaced with #218

**Comment by cosven** [comment]
Thanks for the contribution for the `task_list` extra, but I have different thoughts on the task-list-wrapper-text.

Currently, the task-list-wrapper-text is:
`_task_list_warpper_str = r'<p><input type="checkbox" class="task-list-item-checkbox" %sdisabled>%s</p>'`. In my opinion, the `<p>` tag is unnecessary.

I think the better option will be:
`<input type="checkbox" class="task-list-item-checkbox" disabled>%s`, as github also handles in this way.

I also have a simple comment on that PR: <https://github.com/trentm/python-markdown2/pull/218/files#r100302342>

@liguangsheng @nicholasserra

**Comment by cosven** [comment]
I add a PR here: <https://github.com/trentm/python-markdown2/pull/243>

**Pull request closed without merging**
