### PR TITLE
fix: make tables without body gfm compatible

### LINKED ISSUE #615: Tables not fully compatible with GFM format
**Describe the bug**
Tables not fully compatible with Github Flavoured Markdown format. It returns a paragraph instead of table.

**To Reproduce**
Extracted from GFM [example 205](https://github.github.com/gfm/#example-205)
```
| abc | def |
| --- | --- |
```

Converting the markdown above returns:
```
<p>| abc | def |
| --- | --- |</p>
```

**Expected behavior**
```
<table>
<thead>
<tr>
  <th>abc</th>
  <th>def</th>
</tr>
</thead>
</table>
```
**Debug info**
Version of library being used: 2.5.1

Any extras being used: tables

**Additional context**

### PR DESCRIPTION
**Pull request by raulbocanegra**
fixes #615

### CODE REVIEW

**Comment by nicholasserra** [comment]
Thank you!

**Comment by raulbocanegra** [comment]
You are welcome! I was wondering if there is an expected date for a new release with this fix.

**Comment by nicholasserra** [comment]
We usually wait for a few changes to be implemented before pushing out a release. If this is a high priority item for you we can do a special release. Let me know.

**Comment by raulbocanegra** [comment]
If you could do a new release it could be great. In case you could not do it, I can use my fork meanwhile.

**Comment by nicholasserra** [comment]
@raulbocanegra 2.5.3 has been released

**Pull request merged**
