### PR TITLE
Updated test cases to support Pygments 2.5.1

### LINKED ISSUE #338: Pygment 2.5.1 is breaking test cases
Pygments updated to 2.5.1 early on the 26th. This is breaking some of the unit tests.

I'll make a PR to fix it soon.

### PR DESCRIPTION
**Pull request by ryanvilbrandt**
Resolves #338

### CODE REVIEW

**Comment by ryanvilbrandt** [comment]
I was able to update the test cases, unfortunately Python 3.4 was the odd one out and kept failing after the others were passing. The was able to "fix" the issue by just adding the knownfailure tag to all the failing test cases.

I'm not happy with that solution, especially since this seems like it is likely an issue with Pygments. In my opinion, we should wait a few days to see if Pygments will be fixed. If not, this PR can be merged to ignore those tests.

**Comment by nicholasserra** [comment]
I don't see an update to the pygments installed version in the travis file in this PR. Might be why you're seeing failures

https://github.com/trentm/python-markdown2/blob/master/.travis.yml#L10

**Comment by nicholasserra** [comment]
Well, now I see that it's just fetching latest version. Hm. I definitely don't love the knownfailures additions.

**Comment by ryanvilbrandt** [comment]
I tried rolling back Pygments to version 2.4.2, which was the version that was last working, however I discovered that [Pygments hasn't supported Python 3.4 in its recent releases](https://travis-ci.org/trentm/python-markdown2/jobs/618761634?utm_medium=notification&utm_source=github_status).

Knowing that, I added a check when building the tests to ignore a test if it's tagged "pygments" and the version of Python running is 3.4 or earlier. It's a bit hacky, but the tests are running now.

An alternate option would be to add the ability to create alternate *.html files depending on the version of Python that's running. Let me know if this is a direction you'd prefer.

**Comment by ryanvilbrandt** [comment]
I ended up adding the Python 3.4 specific tests. Everything is passing now! Hooray!

**Comment by nicholasserra** [comment]
To be honest, seems that many packages are dropping 3.4 support, so it would probably be cleaner to just drop that test case in travis. I appreciate the effort in getting 3.4 working, but I'll probably just drop it from the build matrix.

**Pull request closed without merging**
