### PR TITLE
Add support for telegram spoiler in extras

### PR DESCRIPTION
**Pull request by jk6521**
- ||spoiler|| - works
- || spoiler || - doesn't works, need help on this

### CODE REVIEW

**Comment by Crozzers** [comment]
Your regex is off.
```regex
\|\|(?=\S)   # matches "||" followed by a NON-whitespace char
(.+?)        # this bit is fine
(?<=\S)\|\|  # matches "||" preceded by a NON-whitespace char
```
You seem to have used `\S` (non-whitespace) instead of `\s` (whitespace).

I would recommend something like:
```regex
\|\|\s?  # matches "||" followed by an optional whitespace
(.+?)    # same as before
\s?\|\|  # matches an optional whitespace and then "||"
```
This way you can have `|| spoiler ||`, `||spoiler||`, `|| spoiler||` and `||spoiler ||`

**Comment by jk6521** [comment]
> Your regex is off.
> 
> ```regexp
> \|\|(?=\S)   # matches "||" followed by a NON-whitespace char
> (.+?)        # this bit is fine
> (?<=\S)\|\|  # matches "||" preceded by a NON-whitespace char
> ```
> 
> You seem to have used `\S` (non-whitespace) instead of `\s` (whitespace).
> 
> I would recommend something like:
> 
> ```regexp
> \|\|\s?  # matches "||" followed by an optional whitespace
> (.+?)    # same as before
> \s?\|\|  # matches an optional whitespace and then "||"
> ```
> 
> This way you can have `|| spoiler ||`, `||spoiler||`, `|| spoiler||` and `||spoiler ||`

Thanks it really means a lot when persons like me doesn't know much about regex.

**Comment by Crozzers** [comment]
No worries! I usually keep a couple of cheat sheets to hand whenever I write regex. I find myself referring to [activestate's Python regex cheatsheet](https://www.activestate.com/wp-content/uploads/2020/03/Python-RegEx-Cheatsheet.pdf) a lot. [Mozilla's regex cheatsheet](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Cheatsheet) is also very detailed and comprehensive but it's for Javascript, so there may be a couple of differences

**Comment by jk6521** [comment]
@Crozzers help was good but that doesn't solve the issue,

```
markdown2.py didn't produce the expected HTML:
  ---- text (escaping: .=space, \n=newline) ----
    This.is.some.||Telegram.spoiler||.text.\n
    \n
    This.is.some.||Telegram.spoiler.with.more.words.||.text.
  ---- Python markdown2.py HTML (escaping: .=space, \n=newline) ----
    <p>This.is.some.<tg-spoiler>Telegram.spoiler</tg-spoiler>.text.</p>\n
    \n
    <p>This.is.some.<tg-spoiler>Telegram.spoiler.with.more.words</tg-spoiler>.text.</p>\n
  ---- expected HTML (escaping: .=space, \n=newline) ----
    <p>This.is.some.<tg-spoiler>Telegram.spoiler</tg-spoiler>.text.</p>\n
    \n
    <p>This.is.some.<tg-spoiler>.Telegram.spoiler.with.more.words.</tg-spoiler>.text.</p>\n
```

Some help here would be appreciated.

**Comment by Crozzers** [comment]
Did you use the regex example verbatim or did you condense it back down to one line?
If the regex is spread across multiple lines you will need to add the `re.X` flag like so:
```python
_tg_spoiler_re = re.compile(r'''
\|\|\s?  # matches "||" followed by an optional whitespace
(.+?)    # same as before
\s?\|\|  # matches an optional whitespace and then "||"
''', re.S | re.X)
```
Or it can be condensed back into a one-liner like so:
```python
_tg_spoiler_re = re.compile(r"\|\|\s?(.+?)\s?\|\|", re.S)
```

**Comment by jk6521** [comment]
@Crozzers The pattern is exactly the same like the above one and it is one line
```py
_tg_spoiler_re = re.compile(r"\|\|\s?(.+?)\s?\|\|", re.S)
```

I can understand why it's happening, the pattern is matching `|| ` with a space after or before it and replacing it with `<tg-spoiler>` or `</tg-spoiler>`

Sourcecode:
```py
_tg_spoiler_re = re.compile(r"\|\|\s?(.+?)\s?\|\|", re.S)
    def _do_tg_spoiler(self, text):
        text = self._tg_spoiler_re.sub(r"<tg-spoiler>\1</tg-spoiler>", text)
        return text
```

**Comment by Crozzers** [comment]
Just went back and tested on my machine and it works fine. Here is [my working tree](https://github.com/Crozzers/python-markdown2/blob/cf79420b6e5040cd1ba75e8e7480dbb42d6b1502/lib/markdown2.py#L2225).

I amended your test case to include some extra uses like so:
```md
This is some || Telegram spoiler || text.

This is some ||Telegram spoiler|| text.

This is some || Telegram spoiler|| text.

This is some ||Telegram spoiler || text.
```
And this produces exactly the output I expected:
```html
<p>This is some <tg-spoiler>Telegram spoiler</tg-spoiler> text.</p>

<p>This is some <tg-spoiler>Telegram spoiler</tg-spoiler> text.</p>

<p>This is some <tg-spoiler>Telegram spoiler</tg-spoiler> text.</p>

<p>This is some <tg-spoiler>Telegram spoiler</tg-spoiler> text.</p>
```
This seems correct to me.

**Comment by Crozzers** [comment]
Also when you gave this error:
> ```
> markdown2.py didn't produce the expected HTML:
>   ---- text (escaping: .=space, \n=newline) ----
>     This.is.some.||Telegram.spoiler||.text.\n
>     \n
>     This.is.some.||Telegram.spoiler.with.more.words.||.text.
>   ---- Python markdown2.py HTML (escaping: .=space, \n=newline) ----
>     <p>This.is.some.<tg-spoiler>Telegram.spoiler</tg-spoiler>.text.</p>\n
>     \n
>     <p>This.is.some.<tg-spoiler>Telegram.spoiler.with.more.words</tg-spoiler>.text.</p>\n
>   ---- expected HTML (escaping: .=space, \n=newline) ----
>     <p>This.is.some.<tg-spoiler>Telegram.spoiler</tg-spoiler>.text.</p>\n
>     \n
>     <p>This.is.some.<tg-spoiler>.Telegram.spoiler.with.more.words.</tg-spoiler>.text.</p>\n
> ```

In the expected HTML section, it says it expects the output to include the optional spaces before/after the `||` symbols
```
<p>This.is.some.<tg-spoiler>.Telegram.spoiler.with.more.words.</tg-spoiler>.text.</p>\n
                            ^                                ^
                            Optional spaces have been left in
```
The regex I suggested excludes these spaces from the output, and so do the test cases I'm using. I assumed that these optional spaces weren't important and that this would be a desirable behaviour

**Comment by jk6521** [comment]
Yeah they aren't important, shit I was thinking they are so important and that's how I was wasting my time on it.
Thanks man for your help.

**Comment by nicholasserra** [comment]
Thanks!

**Pull request merged**
