### PR TITLE
Added header support for wiki tables

### PR DESCRIPTION
**Pull request by ryanvilbrandt**
Following the syntax used in Wikidot:

```
||~ Head1 ||~ Head2 ||
||  cell1 ||  cell2 ||
```

Also added indenting to match the format found when using the `tables` extra.

### CODE REVIEW

**Comment by nicholasserra** [comment]
Thanks for the PR! Looks like this is failing some tests. Check the CI build :)

**Comment by ryanvilbrandt** [comment]
> 
> 
> Thanks for the PR! Looks like this is failing some tests. Check the CI build :)

Looking into it now.

**Comment by ryanvilbrandt** [comment]
Okay, I believe I've followed all the steps for contributing a PR:

- It must pass PEP8.
- It must include relevant test coverage.
- Bug fixes must include a regression test that exercises the bug.
- The entire test suite must pass.

However, I'm not sure how to handle `The README and/or docs are updated accordingly.` I assume you don't want me to update your wiki until this change is merged in. Should I include the text change in a comment here?

**Comment by nicholasserra** [comment]
Nope no wiki update needed (yet?). I'll take a look at this early next week, thanks!

**Comment by nicholasserra** [comment]
I noticed you had to add `{"extras": ["tables"]}` to the `Tables` test case. Seems tables were working originally without the extra being turned on. So does this PR break backwards compat of built in tables feature?

**Comment by ryanvilbrandt** [comment]
Tables.text is under the "-knownfailure" flag, so it wasn't being tested prior to my change anyways. I ended up fixing it before realizing I should be running the tests with that flag so I don't have to fix a bunch of problems that aren't related to my change. However, that change still manages to get a test working, even if it's not tested by CI, so I decided to leave it in.

**Comment by nicholasserra** [comment]
Thank you and thanks for the clarification :)

**Comment by ryanvilbrandt** [comment]
When do you want the Extras wiki updated? Now that the change is merged into master? Or after you push a new release to pypi?

**Comment by nicholasserra** [comment]
Any time works. I'm not totally sure if that wiki is up to date in general. If you want to take a stab at it, please do, thanks!

**Pull request merged**
