### PR TITLE
support ```<space><lang> for fenced code block

### PR DESCRIPTION
**Pull request by roxma**
This syntax works on github. So I think it's worth sending a PR.

### CODE REVIEW

**Comment by roxma** [comment]
This syntax works on github. So I think it's worth sending a PR.

**Comment by nicholasserra** [comment]
Hello. Thanks for the patch! Can you add a test case for this also? Thank you.

**Comment by skinnyMan** [comment]
Looking forward to this one!

**Comment by skinnyMan** [comment]
@nicholasserra are you still waiting on a test case?

**Comment by nicholasserra** [comment]
Yes, but if this is something that's in demand I could cherry pick it and add my own test.

**Comment by skinnyMan** [comment]
that would be great, i know i have a need for it.

**Comment by nicholasserra** [comment]
Manually merged into master with a test case. Will go out with next release. Thanks!

**Pull request closed without merging**
