### PR TITLE
Breaks improvements and code simplification

### PR DESCRIPTION
**Pull request by m417z**
* Using both a newline and a backslash no longer results in two line breaks.
* Allow to keep using trailing spaces for a line break.
* Remove redundant trailing space before a line break.

### CODE REVIEW

**Comment by nicholasserra** [comment]
Looks like some test failures. @Crozzers if you have a sec would love your eyes on this too thanks!

**Comment by m417z** [comment]
Rebased and fixed WaveDrom tests.

**Comment by Crozzers** [comment]
LGTM. The removal of `if 'breaks' in self.extras` threw me for a bit but that looks to be covered in the `else` clause

**Comment by nicholasserra** [comment]
Thanks!

**Pull request merged**
