### PR TITLE
Add underline 'u' support in extras

### PR DESCRIPTION
**Pull request by starry69**
Signed-off-by: starry69 <starry369126@outlook.com>

### CODE REVIEW

**Comment by nicholasserra** [comment]
Thanks! I need to do some research on `ins` vs `u`. It seems `u` was not well supported, but now html5 supports `u` fully. Depending on that research we may just wanna change this over to `u` and `underline` as extra name.

Have any opinions?

**Comment by starry69** [comment]
Yeah sure I'll do that

**Comment by nicholasserra** [comment]
Let me research first. I'll comment when I figure out what's best.

**Comment by starry69** [comment]
Yeah u will look more better imo as per HTML5 documentation...

**Comment by starry69** [comment]
Hi I've looked in internet and yes I think using 'u' would be better option here since we just want underline text support.. https://html.com/tags/u/ and https://html.com/tags/ins/

**Comment by nicholasserra** [comment]
Cool, looks good. Seeing failing tests on this.

**Comment by starry69** [comment]
Hmmm dunno tbh why test not passing, I've checked code before makeing a PR it seems to work fine tho

**Comment by starry69** [comment]
Sure. I'll check

**Comment by starry69** [comment]
Fixed ;)

**Comment by nicholasserra** [comment]
Thanks!

**Pull request merged**
